package com.realtegic.kora.core.data

import com.realtegic.kora.core.model.CheckoutDto
import com.realtegic.kora.core.model.CreateCheckoutAdjustmentRequest
import com.realtegic.kora.core.model.VoidCheckoutRequest
import com.realtegic.kora.core.network.ApiResult
import com.realtegic.kora.core.network.CheckoutsApi
import com.realtegic.kora.core.network.safeApiCall
import com.squareup.moshi.Moshi

/**
 * Checkout creation requires a stable idempotency key, owned and
 * regenerated by the caller (ViewModel), not this repository -- exact
 * same lifecycle discipline as booking/organization creation (docs
 * task Phase 7: "generate a new key only after the attempt has a known
 * terminal result or the request changes"). If the server reports a
 * checkout already exists, the caller is expected to fetch and display
 * the authoritative one rather than retry blindly.
 */
class CheckoutsRepository(
    private val api: CheckoutsApi,
    private val moshi: Moshi,
) {
    suspend fun create(organizationId: String, serviceSessionId: String, idempotencyKey: String): ApiResult<CheckoutDto> =
        safeApiCall(moshi) { api.create(organizationId, serviceSessionId, idempotencyKey) }

    suspend fun list(
        organizationId: String,
        branchId: String? = null,
        status: String? = null,
        assignedStaffProfileId: String? = null,
        serviceSessionId: String? = null,
    ): ApiResult<List<CheckoutDto>> = safeApiCall(moshi) { api.list(organizationId, branchId, status, assignedStaffProfileId, serviceSessionId = serviceSessionId) }

    /** Looks up the (at most one, DB-unique) checkout for a specific
     * completed service session -- used to recover after a
     * `CHECKOUT_ALREADY_EXISTS` conflict rather than guessing (docs
     * task Phase 7). */
    suspend fun findForServiceSession(organizationId: String, serviceSessionId: String): ApiResult<CheckoutDto?> =
        when (val result = list(organizationId, serviceSessionId = serviceSessionId)) {
            is ApiResult.Success -> ApiResult.Success(result.value.firstOrNull())
            is ApiResult.Failure -> result
        }

    suspend fun get(organizationId: String, checkoutId: String): ApiResult<CheckoutDto> =
        safeApiCall(moshi) { api.get(organizationId, checkoutId) }

    suspend fun addAdjustment(organizationId: String, checkoutId: String, type: String, amountMinor: Long, reason: String): ApiResult<CheckoutDto> =
        safeApiCall(moshi) { api.addAdjustment(organizationId, checkoutId, CreateCheckoutAdjustmentRequest(type, amountMinor, reason)) }

    suspend fun void(organizationId: String, checkoutId: String, reason: String): ApiResult<CheckoutDto> =
        safeApiCall(moshi) { api.void(organizationId, checkoutId, VoidCheckoutRequest(reason)) }
}
