package com.realtegic.kora.core.data

import com.realtegic.kora.core.model.ConfirmPaymentRequest
import com.realtegic.kora.core.model.DisputePaymentRequest
import com.realtegic.kora.core.model.PaymentDisputeDto
import com.realtegic.kora.core.model.PaymentRecordDto
import com.realtegic.kora.core.model.RecordPaymentRequest
import com.realtegic.kora.core.model.ResolvePaymentDisputeRequest
import com.realtegic.kora.core.model.VoidPaymentRequest
import com.realtegic.kora.core.network.ApiResult
import com.realtegic.kora.core.network.PaymentDisputesApi
import com.realtegic.kora.core.network.PaymentsApi
import com.realtegic.kora.core.network.safeApiCall
import com.squareup.moshi.Moshi

/**
 * A [PaymentRecordDto] is only ever a claim (docs task locked rules) --
 * nothing here, or anywhere it is consumed, ever treats a `RECORDED`
 * payment as revenue. Recording requires a stable idempotency key,
 * owned and regenerated by the caller.
 */
class PaymentsRepository(
    private val paymentsApi: PaymentsApi,
    private val disputesApi: PaymentDisputesApi,
    private val moshi: Moshi,
) {
    suspend fun record(
        organizationId: String,
        checkoutId: String,
        idempotencyKey: String,
        request: RecordPaymentRequest,
    ): ApiResult<PaymentRecordDto> = safeApiCall(moshi) { paymentsApi.record(organizationId, checkoutId, idempotencyKey, request) }

    suspend fun list(organizationId: String, checkoutId: String): ApiResult<List<PaymentRecordDto>> =
        safeApiCall(moshi) { paymentsApi.list(organizationId, checkoutId) }

    suspend fun confirm(organizationId: String, paymentId: String, reason: String?): ApiResult<PaymentRecordDto> =
        safeApiCall(moshi) { paymentsApi.confirm(organizationId, paymentId, ConfirmPaymentRequest(reason)) }

    suspend fun dispute(organizationId: String, paymentId: String, reason: String): ApiResult<PaymentRecordDto> =
        safeApiCall(moshi) { paymentsApi.dispute(organizationId, paymentId, DisputePaymentRequest(reason)) }

    suspend fun void(organizationId: String, paymentId: String, reason: String): ApiResult<PaymentRecordDto> =
        safeApiCall(moshi) { paymentsApi.void(organizationId, paymentId, VoidPaymentRequest(reason)) }

    suspend fun pendingVerifications(organizationId: String): ApiResult<List<PaymentRecordDto>> =
        safeApiCall(moshi) { paymentsApi.pendingVerifications(organizationId) }

    suspend fun myVerifications(organizationId: String, status: String? = null): ApiResult<List<PaymentRecordDto>> =
        safeApiCall(moshi) { paymentsApi.myVerifications(organizationId, status) }

    suspend fun listDisputes(organizationId: String, status: String? = null): ApiResult<List<PaymentDisputeDto>> =
        safeApiCall(moshi) { disputesApi.list(organizationId, status) }

    suspend fun getDispute(organizationId: String, disputeId: String): ApiResult<PaymentDisputeDto> =
        safeApiCall(moshi) { disputesApi.get(organizationId, disputeId) }

    suspend fun resolveDispute(organizationId: String, disputeId: String, resolution: String, resolutionNote: String?): ApiResult<PaymentDisputeDto> =
        safeApiCall(moshi) { disputesApi.resolve(organizationId, disputeId, ResolvePaymentDisputeRequest(resolution, resolutionNote)) }
}
